name = "WidenableArrays"
uuid = "e204200e-d7ba-4b7e-bfa9-053a2e530198"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[deps]
Derive = "a07dfc7f-7d04-4eb5-84cc-a97f051f655a"

[compat]
Derive = "0.3.6"
julia = "1.10"
