name = "WidenableArrays"
uuid = "e204200e-d7ba-4b7e-bfa9-053a2e530198"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Derive = "a07dfc7f-7d04-4eb5-84cc-a97f051f655a"

[compat]
ArrayLayouts = "1.11.0"
BlockArrays = "1.3.0"
Derive = "0.3.6"
julia = "1.10"
